# yaml 配置
version: "3.7"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    volumes:
        - ./docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/:ro
        - ./docker/mongodb/data/db/:/data/db/
        - ./docker/mongodb/data/log/:/var/log/mongodb
        - ./docker/mongodb/mongod.conf:/etc/mongod.conf
    env_file:
        - .env
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
        - "27017:27017"
    command:
      # - '--auth'
      - '-f'
      - '/etc/mongod.conf'
    # networks:
    #   - share-net
  # redis:
  #   image: redis:4.0.13 
  #   container_name: redis
  #   restart: always
  #   command: --requirepass 123123 --appendonly yes
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ~/data/mongodb/redis_data:/data
  #   networks:
  #     - share-net
  # server: 
  #   container_name: server
  #   restart: always                        # 重启策略: 容器退出时总是重启容器
  #   build: 
  #     context: .                           # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
  #     dockerfile: ./docker/server/Dockerfile
  #   depends_on:
  #     - mongo
  #     - redis
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - share-net
  # web:                                  # 前端node容器(运行nginx中的Vue项目)
  #   container_name: web           # 容器名为'share-client'
  #   restart: always                        # 重启策略: 容器退出时总是重启容器
  #   build:
  #     context: .                           # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
  #     dockerfile: ./docker/client/Dockerfile
  #   environment:
  #     TZ: Asia/Shanghai
  #   ports:
  #     - "80:80"                        # 映射端口
  #   volumes:
  #     - ~/data/nginx/logs:/var/log/nginx
  #   depends_on:                            # 依赖于容器，被依赖容器启动后此web容器才可启动
  #     - server
  #   networks:
  #     - share-net
  # admin:                                  # 前端node容器(运行nginx中的Vue项目)
  #   container_name: admin           # 容器名为'share-client'
  #   restart: always                        # 重启策略: 容器退出时总是重启容器
  #   build:
  #     context: .                           # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
  #     dockerfile: ./docker/client/Dockerfile
  #   environment:
  #     TZ: Asia/Shanghai
  #   ports:
  #     - "3000:3000"                        # 映射端口
  #   volumes:
  #     - ~/data/nginx/logs:/var/log/nginx
  #   depends_on:                            # 依赖于容器，被依赖容器启动后此web容器才可启动
  #     - server
  #   networks:
  #     - share-net
# networks:
#   share-net:
    # name: share-net