# yaml 配置
version: "3.7"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    volumes:
        - ./docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/:ro
        - ~/data/mongodb/db:/data/db/
        - ~/data/mongodb/log/:/var/log/mongodb
        - ./docker/mongodb/mongod.conf:/etc/mongod.conf
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: ant_blog
    ports:
        - "27017:27017"
    command:
      - '-f'
      - '/etc/mongod.conf'
    networks:
      - share-net
  redis:
    image: redis:5.0.0
    container_name: redis
    restart: always
    command: --requirepass 123456 --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ~/data/redis:/data
    networks:
      - share-net
  server: 
    container_name: server
    restart: always                        # 重启策略: 容器退出时总是重启容器
    build: 
      context: .                           # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: ./docker/server/Dockerfile
    depends_on:
      - mongodb
      - redis
    ports:
      - "7001:7001"
    networks:
      - share-net
  web:                                  # 前端node容器(运行nginx中的Vue项目)
    container_name: web           # 容器名为'web'
    restart: always                        # 重启策略: 容器退出时总是重启容器
    build:
      context: .                           # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: ./docker/web/Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "80:80"                        # 映射端口
    volumes:
      - ~/data/nginx/logs:/var/log/nginx
    depends_on:                            # 依赖于容器，被依赖容器启动后此web容器才可启动
      - server
    networks:
      - share-net
  admin:                                  # 前端node容器(运行nginx中的Vue项目)
    container_name: admin           # 容器名为'share-client'
    restart: always                        # 重启策略: 容器退出时总是重启容器
    build:
      context: .                           # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: ./docker/admin/Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "3000:3000"                        # 映射端口
    volumes:
      - ~/data/nginx/logs:/var/log/nginx
    depends_on:                            # 依赖于容器，被依赖容器启动后此web容器才可启动
      - server
    networks:
      - share-net
networks:
  share-net:
    name: share-net